#!/usr/bin/env python3
"""Generate DarwinX evolution-smoke configs from onboarded agent manifests.

This is the evolution counterpart to ``scripts/generate_eval_configs.py``. It reuses that
script's agent/benchmark matrix, version-to-manifest join, public/internal provider profiles,
and seeded two-task samples, then writes the evolution role shape:
``evolvee`` + ``evolver`` + ``algorithm`` + ``data``.

Generated files live beside evaluation smokes under ``tests/smoke/<benchmark>/`` and are
gitignored. Checked-in files under ``examples/evolution/`` remain schema-oriented teaching
material and never receive a user's repository or commit.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
CANONICAL = REPO_ROOT / "scripts" / "generate_eval_configs.py"
SMOKE_ROOT = REPO_ROOT / "tests" / "smoke"
MANIFEST_DIR = REPO_ROOT / ".beagle" / "agents"
SUFFIX = "darwinx_evolution_smoke2"


def _load_canonical():
    """Load the eval generator as a module so matrix/profile facts stay single-source."""
    spec = importlib.util.spec_from_file_location("canonical_eval_gen", CANONICAL)
    assert spec and spec.loader, f"cannot load {CANONICAL}"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gen = _load_canonical()

SMOKE_HPARAMS: dict[str, Any] = {
    # One node with one proposal attempt. Omit total_steps so the smoke stays a single node.
    "max_loop_iters": 1,
    "n_failure_tasks": 1,
    "mini_eval_k_samples": 1,
    # best-of-1 is one final sample. avg uses the driver's separate avg@k path.
    "fullset_eval_n_attempts": 1,
    "fullset_metric": "best",
    "guard_enabled": True,
    "anti_cheat": True,
}


def _required(manifest: dict[str, Any], key: str, label: str) -> Any:
    value = manifest.get(key)
    if value in (None, ""):
        raise ValueError(
            f"manifest for {label} has no {key!r}; re-run onboarding with an explicit "
            f"--{key.replace('_', '-')} value"
        )
    return value


def build_config(
    agent: str,
    benchmark: str,
    manifest: dict[str, Any],
    *,
    version: str,
    internal: bool = False,
) -> dict[str, Any]:
    """Build one two-task DarwinX smoke from the canonical eval-smoke cell."""
    base = gen.build_config(
        agent,
        benchmark,
        manifest,
        smoke=True,
        version=version,
        internal=internal,
    )
    label = gen._label(agent, version)
    source = dict(base["agent"]["harness"]["source"])
    source["dir"] = _required(manifest, "dir", label)
    if manifest.get("upstream"):
        source["upstream"] = manifest["upstream"]
    base["agent"]["harness"]["source"] = source

    run = base["run"]
    return {
        "run": {
            "dir": run["dir"],
            "name": f"{label}-{gen.BENCHMARKS[benchmark]['short']}-{SUFFIX}",
            "runtime": run["runtime"],
            "parallelism": run["parallelism"],
        },
        "evolvee": base["agent"],
        "evolver": {
            "harness": {"name": "cursor-agent"},
            "model": {"name": "gpt-5.5-high" if internal else "auto"},
        },
        "algorithm": {"name": "darwinx", "hparams": dict(SMOKE_HPARAMS)},
        "data": base["data"],
    }


def validate_config(raw: dict[str, Any]) -> None:
    """Validate both the canonical evolution shape and DarwinX's typed hparams."""
    import beagle as bgl
    from beagle.cli._canonical import build_evolution

    cfg, _run_dir, _run_name = build_evolution(raw)
    bgl.algorithms.build(cfg.algorithm.name, **dict(cfg.algorithm.hparams))


def _dump(agent: str, benchmark: str, raw: dict[str, Any]) -> str:
    return (
        f"# {agent} on {benchmark} — GENERATED by scripts/generate_evolution_config.py.\n"
        "# Two-task DarwinX plumbing smoke; not a benchmark result.\n"
        "# Edit examples/evolution/ or an experiments/configs/ copy for a real campaign.\n"
        "# Parameter guidance: docs/darwinx-configuration.md\n"
        + yaml.safe_dump(raw, sort_keys=False, default_flow_style=False, width=100)
    )


def _selected_cells(*, internal: bool, labels: list[str] | None):
    cells = list(gen.agent_cells(internal=internal))
    if labels is None:
        return cells
    available = {label for _agent, _version, label in cells}
    unknown = sorted(set(labels) - available)
    if unknown:
        raise ValueError(
            f"unknown agent copy: {', '.join(unknown)}; available: {', '.join(sorted(available))}"
        )
    wanted = set(labels)
    return [cell for cell in cells if cell[2] in wanted]


def generate(
    *,
    manifest_dir: Path = MANIFEST_DIR,
    out_root: Path = SMOKE_ROOT,
    internal: bool = False,
    labels: list[str] | None = None,
    benchmarks: list[str] | None = None,
    check: bool = False,
) -> tuple[int, list[str]]:
    """Generate one evolution smoke per selected experiment copy × benchmark."""
    manifests = gen._manifests_by_version(manifest_dir)
    cells = _selected_cells(internal=internal, labels=labels)
    selected_benchmarks = benchmarks or list(gen.BENCHMARKS)
    unknown_benchmarks = sorted(set(selected_benchmarks) - set(gen.BENCHMARKS))
    if unknown_benchmarks:
        raise ValueError(
            f"unknown benchmark: {', '.join(unknown_benchmarks)}; available: "
            f"{', '.join(gen.BENCHMARKS)}"
        )

    missing = [f"{label} ({version})" for _agent, version, label in cells
               if version not in manifests]
    resolved = [(agent, version, label, manifests[version])
                for agent, version, label in cells if version in manifests]
    written = 0
    print(f"[gen-evolve] smoke configs → {out_root}")
    for agent, version, label, manifest in resolved:
        for benchmark in selected_benchmarks:
            raw = build_config(
                agent, benchmark, manifest, version=version, internal=internal,
            )
            validate_config(raw)
            dest = out_root / benchmark / f"{label}_{SUFFIX}.yaml"
            print(f"  {'would write' if check else '✓'} {dest}")
            if not check:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(_dump(agent, benchmark, raw), encoding="utf-8")
            written += 1
    return written, missing


def main(argv: list[str] | None = None) -> int:
    all_labels = sorted({
        label for internal in (False, True)
        for _agent, _version, label in gen.agent_cells(internal=internal)
    })
    parser = argparse.ArgumentParser(
        description="Generate two-task DarwinX evolution smokes from onboarded manifests."
    )
    parser.add_argument(
        "--out",
        default=str(SMOKE_ROOT),
        metavar="DIR",
        help="output root (default: tests/smoke)",
    )
    parser.add_argument(
        "--manifest-dir",
        default=str(MANIFEST_DIR),
        metavar="DIR",
        help="where onboarding wrote manifests (default: .beagle/agents)",
    )
    parser.add_argument(
        "--internal",
        action="store_true",
        help="include internal harnesses and use the internal provider/runtime profile",
    )
    parser.add_argument("--agents", nargs="+", choices=all_labels, metavar="COPY")
    parser.add_argument(
        "--benches",
        nargs="+",
        choices=sorted(gen.BENCHMARKS),
        metavar="BENCHMARK",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="list outputs and missing manifests without writing",
    )
    args = parser.parse_args(argv)

    try:
        written, missing = generate(
            manifest_dir=Path(args.manifest_dir),
            out_root=Path(args.out),
            internal=args.internal,
            labels=args.agents,
            benchmarks=args.benches,
            check=args.check,
        )
    except ValueError as exc:
        parser.error(str(exc))

    print(f"[gen-evolve] {'would generate' if args.check else 'generated'} {written} config(s)")
    if missing:
        print(
            f"[gen-evolve] not onboarded (skipped): {', '.join(missing)} — onboard with the "
            "matching --version, then re-run",
            file=sys.stderr,
        )
        if args.check:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
